force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker C</label>
    <nameField>
        <label>Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker_W9_Form__c/Speaker_W9_Form__c.object-meta.xml
<CustomObject>
    <label>Speaker W9 Form</label>
    <nameField>
        <displayFormat>SWF-{0000}</displayFormat>
        <label>Speaker W9 Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speaker W9 Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker_W9_Form__c/fields/Form_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Form_Expiration_Date__c</fullName>
    <label>Form Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Speaker_W9_Form__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Speaker W9 Forms</relationshipLabel>
    <relationshipName>Speaker_W9_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SpeakerW9FormExpirationWarningController.cls
/**
 * Created by Dima on 26.08.2020.
 */

public with sharing class SpeakerW9FormExpirationWarningController {
    @AuraEnabled
    public static Boolean isW9FormGoingToBeExpired(String speakerId) {
        List<Speaker_W9_Form__c> w9FormList = [SELECT Form_Expiration_Date__c FROM Speaker_W9_Form__c WHERE Speaker__c =: speakerId ORDER BY Form_Expiration_Date__c DESC];
        system.debug('w9FormList.size() -> ' + w9FormList.size());
        if(w9FormList.size() > 0){
            Speaker_W9_Form__c w9Form = w9FormList.get(0);
            system.debug('w9Form.Form_Expiration_Date__c -> ' + w9Form.Form_Expiration_Date__c );
            system.debug('System.today() ' + System.today() + '; System.today().addMonths(1)' + System.today().addMonths(1));
            if(w9Form.Form_Expiration_Date__c >= System.today() && w9Form.Form_Expiration_Date__c <= System.today().addMonths(1)){
                return true;
            }
        }

        return false;
    }
}