force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_From_Suggested_Meeting_Speaker__c/Response_From_Suggested_Meeting_Speaker__c.object-meta.xml
<CustomObject>
    <label>Response From Suggested Meeting Speaker</label>
    <nameField>
        <displayFormat>RFSMS-{0000}</displayFormat>
        <label>Response From Suggested Meeting Speaker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses From Suggested Meeting Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_From_Suggested_Meeting_Speaker__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Responses From Suggested Meeting Speaker</relationshipLabel>
    <relationshipName>Responses_From_Suggested_Meeting_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response_From_Suggested_Meeting_Speaker__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I&apos;m interested</fullName>
            </value>
            <value>
                <fullName>Please, send me additional info</fullName>
            </value>
            <value>
                <fullName>I don&apos;t want to visit this meeting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_From_Suggested_Meeting_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Responses From Suggested Meeting Speaker</relationshipLabel>
    <relationshipName>Responses_From_Suggested_Meeting_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker C</label>
    <nameField>
        <label>Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectResponseFromSpeakerController.cls
/**
 * Created by Dima on 18.08.2020.
 */

public with sharing class CollectResponseFromSpeakerController {
    public Boolean isSend {get; set;}
    public String meetingId {get; set;}
    public String speakerId {get; set;}
    public String varResponse {get; set;}
    public String varComment {get; set;}

    public CollectResponseFromSpeakerController() {
        isSend = false;

        meetingId = ApexPages.currentPage().getParameters().get('meetingId');
        speakerId = ApexPages.currentPage().getParameters().get('speakerId');
    }

    public void saveResponse() {
        isSend = true;

        Response_From_Suggested_Meeting_Speaker__c responseFromSuggestedMeetingSpeaker = new Response_From_Suggested_Meeting_Speaker__c();
        responseFromSuggestedMeetingSpeaker.Meeting__c = meetingId;
        responseFromSuggestedMeetingSpeaker.Speaker__c = speakerId;
        responseFromSuggestedMeetingSpeaker.Response__c = varResponse;
        responseFromSuggestedMeetingSpeaker.Comment__c = varComment;
        insert responseFromSuggestedMeetingSpeaker;
    }
}